export enum OrderStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  PROCESSED = "PROCESSED",
  DELIVERED = "DELIVERED",
  RETURNED = "RETURNED",
  PARTIAL_RETURNED = "PARTIAL_RETURNED",
  CANCELED = "CANCELED",
  COMPLETED = "COMPLETED",
}
